name: CI/CD
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    steps:
      - uses: actions/checkout@v4
      
      - name: build
        run: |
          set -xeuo pipefail
          dnf -y install 'dnf-command(config-manager)'
          dnf -y config-manager --set-enabled crb
          dnf -y install go-toolset libvirt-devel
          export GOPROXY=https://proxy.golang.org
          go install github.com/onsi/ginkgo/v2/ginkgo@latest
          go install github.com/cpuguy83/go-md2man@latest
          make GOOPTS=-buildvcs=false
          export PATH=$PATH:$HOME/go/bin
          make integration_tests

      - name: lint
        run: |
          curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.61.0
          export PATH=$PATH:$HOME/go/bin
          make lint

      - name: gofmt
        run: |
          if test -z $(gofmt -l .); then exit 0; else gofmt -d -e . && exit 1; fi

  release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/v')
    runs-on: ubuntu-latest
    container: quay.io/centos/centos:stream9
    steps:
      - uses: actions/checkout@v4
      
      - name: Build Release Binary
        run: |
          set -xeuo pipefail
          dnf -y install 'dnf-command(config-manager)'
          dnf -y config-manager --set-enabled crb
          dnf -y install go-toolset libvirt-devel
          make GOOPTS=-buildvcs=false

      - name: Create Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            bin/podman-bootc
          generate_release_notes: true
